// This file is GENERATED by buildPlugin.mjs script
import {PluginEnv} from "lib/plugin/PluginEnv"
export const PLUGIN_ENV = new PluginEnv({
    env: "prod",
    pluginName: "POS_ENGINE_PLUGIN",
    pluginId: "8Events_Plugins__POS_ENGINE_PLUGIN__v0_1_0",
    pluginVersion: "0.1.0",
    author: "8Events"
})
